[package]
name = "telegram-bot-torrents"
version = "0.2.1"
authors = ["Guilherme Henrique <gjhenrique@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
telegram-bot = { git = "https://github.com/telegram-rs/telegram-bot", default-features = false, features = ["rustls"] }

futures = "0.3"
tokio = { version = "1.2", features = ["full"]}
hyper = "0.14"
hyper-rustls = "0.22"
serde_json = "1.0"
serde = "1.0"
url = "2.2.0"
size_format = "1.0"
