name: Release binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install cross
      run: cargo install cross
    - name: Compile x86 binary
      run: |
        cross build --release --target=x86_64-unknown-linux-gnu
        cp target/x86_64-unknown-linux-gnu/release/torrent-bot telegram-bot-torrents.linux.x86
    - name: Compile arm binary
      run: |
        cross build --release --target=arm-unknown-linux-gnueabihf
        cp target/arm-unknown-linux-gnueabihf/release/torrent-bot telegram-bot-torrents.linux.armv6
    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: telegram-bot-torrents*

  release:
    runs-on: ubuntu-latest
    needs: ['build']
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: binaries
          path: .

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: telegram-bot-torrents*
          file_glob: true
          asset_name: file
          tag: ${{ github.ref }}
          overwrite: true
